// This is a new Employee_1.cpp
// Note the following items:
// 1. inclusion of header file
// 2. functions are actually generated by clicking the hints in .hpp file

#include "Employee_1.hpp"

// this is the constructor function
Employee::Employee(std::string n, int p, Date d)
{
    name = n; // LHS is attribute name, RHS is constructor arg
    hourly_paid = p;
    starting_day = d;
} // as from the name, constructor initializes the object
// by assigning the args to object's private attributes

// Below is a better way for constructor function: in-line constructor
// Employee::Employee(): name(n), hourly_paid(p), starting_day(d)
// {
// }

std::string Employee::get_name() const
{
    return name; // private attribute name can be used since Employee class private definition is visible
} // if you declare and then return "std::string name; return name;", it would be an error

int Employee::get_hourly_rate() const
{
    return hourly_paid; // private attribute hourly_paid can be used, see above
}

Date Employee::get_starting_date() const
{
    return starting_day; // private attribute starting_day can be used, see above
}